// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "R/Du5TwfY3(c$#y:fZ31":
            case "Player Basic":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . d d d . . . 
. . . . d d d d d d d f d . . . 
. . . . d f f f f f f f d . . . 
. . . d d f f f f f f f d . . . 
. . d d f f f f f f d d d . . . 
. . d f f f f f f f d . . . . . 
. . d f f f f f f f d . . . . . 
. . d f f f f f f f d . . . . . 
. . d f f d d f f d d . . . . . 
d d d f f d d f f d d d d . . . 
d f f f f f f f f f d f d . . . 
. d f f f f f f f f d d . . . . 
. . d f f f f f f f d . . . . . 
. . d f f d d d f f d . . . . . 
. . d d d d . d d d d . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "Jump Animation":
            case "anim1":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . d d d . . . 
. . . . d d d d d d d f d . . . 
. . . . d f f f f f f f d . . . 
. . . d d f f f f f f f d . . . 
. . d d f f f f f f d d d . . . 
. . d f f f f f f f d . . . . . 
. . d f f f f f f f d . . . . . 
. . d f f f f f f f d . . . . . 
. . d f f d d f f d d . . . . . 
d d d f f d d f f d d d d . . . 
d f f f f f f f f f d f d . . . 
. d f f f f f f f f d d . . . . 
. . d f f f f f f f d . . . . . 
. . d f f d d d f f d . . . . . 
. . d d d d . d d d d . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . d d d . . . 
. . . . d d d d d d d f d . . . 
. . . . d f f f f f f f d . . . 
. . . d d f f f f f f f d . . . 
. . d d f f f f f f d d d . . . 
. . d f f f f f f f d . . . . . 
. . d f f f f f f f d . . . . . 
. . d f f d d f f d d . . . . . 
d d d f f d d f f d d d d . . . 
d f f f f f f f f f d f d . . . 
. d f f f f f f f f d d . . . . 
. . d f f d d d f f d . . . . . 
. . d d d d . d d d d . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . d d d . . . 
. . . . d d d d d d d f d . . . 
. . . . d f f f f f f f d . . . 
. . . d d f f f f f f f d . . . 
. . d d f f f f f f d d d . . . 
. . d f f f f f f f d . . . . . 
. . d f f d d f f d d . . . . . 
d d d f f d d f f d d d d . . . 
d f f f f f f f f f d f d . . . 
. d d f f d d d f f d d . . . . 
. . d d d d . d d d d . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . d d d . . . 
. . . . d d d d d d d f d . . . 
. . . . d f f f f f f f d . . . 
. . . d d f f f f f f f d . . . 
. . d d f f f f f f d d d . . . 
. . d f f d d f f d d . . . . . 
d d d f f d d f f d d d d . . . 
d f f f f f f f f f d f d . . . 
. d d d d d d d d d d d . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . d d d . . . 
. . . . d d d d d d d f d . . . 
. . . . d f f f f f f f d . . . 
. . . d d f f f f f f f d . . . 
. . d d f f f f f f d d d . . . 
. . d f f d d f f d d . . . . . 
. . d d f d d f f d d . . . . . 
. . d f f f f f f f d . . . . . 
. . d d d d d d d d d . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . d d d . . . 
. . . . d d d d d d d f d . . . 
. . . . d f f f f f f f d . . . 
. . . d d f f f f f f f d . . . 
. . d d f f f f f f d d d . . . 
. . d f f d d f f d d . . . . . 
. . d d f d d f f d d . . . . . 
. . d f f f f f f f d . . . . . 
. . d d d d d d d d d . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . d d d . . . 
. . . . d d d d d d d f d . . . 
. . . . d f f f f f f f d . . . 
. . . d d f f f f f f f d . . . 
. . d d f f f f f f d d d . . . 
. . d f f d d f f d d . . . . . 
. . d d f d d f f d d . . . . . 
. . d f f f f f f f d . . . . . 
. . d d d d d d d d d . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . d d d . . . 
. . . . d d d d d d d f d . . . 
. . . . d f f f f f f f d . . . 
. . . d d f f f f f f f d . . . 
. . d d f f f f f f d d d . . . 
. . d f f d d f f d d . . . . . 
. . d d f d d f f d d . . . . . 
. . d f f f f f f f d . . . . . 
. . d d d d d d d d d . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . d d d . . . 
. . . . d d d d d d d f d . . . 
. . . . d f f f f f f f d . . . 
. . . d d f f f f f f f d . . . 
. . d d f f f f f f d d d . . . 
. . d f f d d f f d d . . . . . 
. . d d f d d f f d d . . . . . 
. . d f f f f f f f d . . . . . 
. . d d d d d d d d d . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . d d d . . . 
. . . . d d d d d d d f d . . . 
. . . . d f f f f f f f d . . . 
. . . d d f f f f f f f d . . . 
. . d d f f f f f f d d d . . . 
. . d f f d d f f d d . . . . . 
. . d d f d d f f d d . . . . . 
. . d f f f f f f f d . . . . . 
. . d d d d d d d d d . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . d d d . . . 
. . . . d d d d d d d f d . . . 
. . . . d f f f f f f f d . . . 
. . . d d f f f f f f f d . . . 
. . d d f f f f f f d d d . . . 
. . d f f d d f f d d . . . . . 
. . d d f d d f f d d . . . . . 
. . d f f f f f f f d . . . . . 
. . d d d d d d d d d . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . d d d . . . 
. . . . d d d d d d d f d . . . 
. . . . d f f f f f f f d . . . 
. . . d d f f f f f f f d . . . 
. . d d f f f f f f d d d . . . 
. . d f f d d f f d d . . . . . 
. . d d f d d f f d d . . . . . 
. . d f f f f f f f d . . . . . 
. . d d d d d d d d d . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . d d d . . . 
. . . . d d d d d d d f d . . . 
. . . . d f f f f f f f d . . . 
. . . d d f f f f f f f d . . . 
. . d d f f f f f f d d d . . . 
. . d f f d d f f d d . . . . . 
. . d d f d d f f d d . . . . . 
. . d f f f f f f f d . . . . . 
. . d d d d d d d d d . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . d d d . . . 
. . . . d d d d d d d f d . . . 
. . . . d f f f f f f f d . . . 
. . . d d f f f f f f f d . . . 
. . d d f f f f f f d d d . . . 
. . d f f d d f f d d . . . . . 
. . d d f d d f f d d . . . . . 
. . d f f f f f f f d . . . . . 
. . d d d d d d d d d . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . d d d . . . 
. . . . d d d d d d d f d . . . 
. . . . d f f f f f f f d . . . 
. . . d d f f f f f f f d . . . 
. . d d f f f f f f d d d . . . 
. . d f f d d f f d d . . . . . 
. . d d f d d f f d d . . . . . 
. . d f f f f f f f d . . . . . 
. . d d d d d d d d d . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . d d d . . . 
. . . . d d d d d d d f d . . . 
. . . . d f f f f f f f d . . . 
. . . d d f f f f f f f d . . . 
. . d d f f f f f f d d d . . . 
. . d f f d d f f d d . . . . . 
. . d d f d d f f d d . . . . . 
. . d f f f f f f f d . . . . . 
. . d d d d d d d d d . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . d d d . . . 
. . . . d d d d d d d f d . . . 
. . . . d f f f f f f f d . . . 
. . . d d f f f f f f f d . . . 
. . d d f f f f f f d d d . . . 
. . d f f d d f f d d . . . . . 
. . d d f d d f f d d . . . . . 
. . d f f f f f f f d . . . . . 
. . d d d d d d d d d . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . d d d . . . 
. . . . d d d d d d d f d . . . 
. . . . d f f f f f f f d . . . 
. . . d d f f f f f f f d . . . 
. . d d f f f f f f d d d . . . 
. . d f f d d f f d d . . . . . 
. . d d f d d f f d d . . . . . 
. . d f f f f f f f d . . . . . 
. . d d d d d d d d d . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . d d d . . . 
. . . . d d d d d d d f d . . . 
. . . . d f f f f f f f d . . . 
. . . d d f f f f f f f d . . . 
. . d d f f f f f f d d d . . . 
. . d f f d d f f d d . . . . . 
d d d f f d d f f d d d d . . . 
d f f f f f f f f f d f d . . . 
. d d d d d d d d d d d . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . d d d . . . 
. . . . d d d d d d d f d . . . 
. . . . d f f f f f f f d . . . 
. . . d d f f f f f f f d . . . 
. . d d f f f f f f d d d . . . 
. . d f f f f f f f d . . . . . 
. . d f f d d f f d d . . . . . 
d d d f f d d f f d d d d . . . 
d f f f f f f f f f d f d . . . 
. d d f f d d d f f d d . . . . 
. . d d d d . d d d d . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . d d d . . . 
. . . . d d d d d d d f d . . . 
. . . . d f f f f f f f d . . . 
. . . d d f f f f f f f d . . . 
. . d d f f f f f f d d d . . . 
. . d f f f f f f f d . . . . . 
. . d f f f f f f f d . . . . . 
. . d f f d d f f d d . . . . . 
d d d f f d d f f d d d d . . . 
d f f f f f f f f f d f d . . . 
. d f f f f f f f f d d . . . . 
. . d f f d d d f f d . . . . . 
. . d d d d . d d d d . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . d d d . . . 
. . . . d d d d d d d f d . . . 
. . . . d f f f f f f f d . . . 
. . . d d f f f f f f f d . . . 
. . d d f f f f f f d d d . . . 
. . d f f f f f f f d . . . . . 
. . d f f f f f f f d . . . . . 
. . d f f f f f f f d . . . . . 
. . d f f d d f f d d . . . . . 
d d d f f d d f f d d d d . . . 
d f f f f f f f f f d f d . . . 
. d f f f f f f f f d d . . . . 
. . d f f f f f f f d . . . . . 
. . d f f d d d f f d . . . . . 
. . d d d d . d d d d . . . . . 
`];
            case "Death Animation":
            case "anim2":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . d d d . . . 
. . . . d d d d d d d f d . . . 
. . . . d f f f f f f f d . . . 
. . . d d f f f f f f f d . . . 
. . d d f f f f f f d d d . . . 
. . d f f f f f f f d . . . . . 
. . d f f f f f f f d . . . . . 
. . d f f f f f f f d . . . . . 
. . d f f d d f f d d . . . . . 
d d d f f d d f f d d d d . . . 
d f f f f f f f f f d f d . . . 
. d f f f f f f f f d d . . . . 
. . d f f f f f f f d . . . . . 
. . d f f d d d f f d . . . . . 
. . d d d d . d d d d . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . d d d . . . 
. . . . d d d d d d d f d . . . 
. . . . d f f f f f f f d . . . 
. . . d d f f f f f f f d . . . 
. . d d f f f f f f d d d . . . 
. . d f f f f f f f d . . . . . 
. . d f f f f f f f d . . . . . 
. . d f f f f f f f d . . . . . 
. . d f f d d f f d d . . . . . 
d d d f f d d f f d d d d . . . 
d f f f f f f f f f d f d . . . 
. d f f f f f f f f d d . . . . 
. . d f f f f f f f d . . . . . 
. . d f f d d d f f d . . . . . 
. . d d d d . d d d d . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . d d 2 . . . 
. . . . d d d d d d d f 2 . . . 
. . . . d f f f f f f f 2 . . . 
. . . d d f f f f f f f 2 . . . 
. . d d f f f f f f d d 2 . . . 
. . d f f f f f f f d . . . . . 
. . d f f f f f f f d . . . . . 
. . d f f f f f f f d . . . . . 
. . d f f d d f f d d . . . . . 
d d d f f d d f f d d d 2 . . . 
d f f f f f f f f f d f 2 . . . 
. d f f f f f f f f d d . . . . 
. . d f f f f f f f d . . . . . 
. . d f f d d d f f d . . . . . 
. . d d d d . d d d d . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . 2 2 2 . . . 
. . . . d d d d d d d f 2 . . . 
. . . . d f f f f f f 2 2 . . . 
. . . d d f f f f f f f 2 . . . 
. . d d f f f f f f 2 2 2 . . . 
. . d f f f f f f f d . . . . . 
. . d f f f f f f f d . . . . . 
. . d f f f f f f f d . . . . . 
. . d f f d d f f d d . . . . . 
d d d f f d d f f d d 2 2 . . . 
d f f f f f f f f f 2 2 2 . . . 
. d f f f f f f f f d 2 . . . . 
. . d f f f f f f f d . . . . . 
. . d f f d d d f f d . . . . . 
. . d d d d . d 2 2 2 . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . 2 2 2 . . . 
. . . . d 2 2 2 2 2 2 f 2 . . . 
. . . . d f f f f 2 2 2 2 . . . 
. . . d d f 2 2 2 f f f 2 . . . 
. . d d f f f f f f 2 2 2 . . . 
. . d f f f f f f f 2 . . . . . 
. . d f f f f 2 2 2 2 . . . . . 
. . d f f f f f f f 2 . . . . . 
. . d f 2 2 2 f 2 2 2 . . . . . 
d d d f 2 2 2 f f 2 2 2 2 . . . 
d f f f f f f f f f 2 2 2 . . . 
. d f f f f f f 2 2 2 2 . . . . 
. . d f f f f f f f 2 . . . . . 
. . d 2 2 2 d 2 2 2 2 . . . . . 
. . d d d 2 . d 2 2 2 . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . 2 2 2 . . . 
. . . . 2 2 2 2 2 2 2 f 2 . . . 
. . . . d f f f f 2 2 2 2 . . . 
. . . d 2 2 2 2 2 f f f 2 . . . 
. . d d f f f f f f 2 2 2 . . . 
. . d f f f f f f f 2 . . . . . 
. . d f 2 2 2 2 2 2 2 . . . . . 
. . d f f f f f f f 2 . . . . . 
. . 2 2 2 2 2 f 2 2 2 . . . . . 
2 2 2 2 2 2 2 f f 2 2 2 2 . . . 
d f f f f f f f f f 2 2 2 . . . 
. d f 2 f 2 2 2 2 2 2 2 . . . . 
. . d f f f f f f f 2 . . . . . 
. . 2 2 2 2 2 2 2 2 2 . . . . . 
. . d 2 2 2 . 2 2 2 2 . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . 2 2 2 . . . 
. . . . 2 2 2 2 2 2 2 f 2 . . . 
. . . . 2 f f f f 2 2 2 2 . . . 
. . . 2 2 2 2 2 2 f f f 2 . . . 
. . 2 2 f f f f f f 2 2 2 . . . 
. . 2 f f f f f f f 2 . . . . . 
. . 2 f 2 2 2 2 2 2 2 . . . . . 
. . 2 f f f f f f f 2 . . . . . 
. 2 2 2 2 2 2 f 2 2 2 . . . . . 
2 2 2 2 2 2 2 f f 2 2 2 2 . . . 
2 f f f f f f f f f 2 2 2 . . . 
. 2 f 2 f 2 2 2 2 2 2 2 . . . . 
. . 2 f f f f f f f 2 . . . . . 
. . 2 2 2 2 2 2 2 2 2 . . . . . 
. . 2 2 2 2 . 2 2 2 2 . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . 2 2 2 . . . 
. . . . 2 2 2 2 2 2 2 f 2 . . . 
. . . . 2 f f f f 2 2 2 2 . . . 
. . . 2 2 2 2 2 2 f f f 2 . . . 
. . 2 2 f f f f f f 2 2 2 . . . 
. . 2 f f f f f f f 2 . . . . . 
. . 2 f 2 2 2 2 2 2 2 . . . . . 
. . 2 f f f f f f f 2 . . . . . 
. 2 2 2 2 2 2 f 2 2 2 . . . . . 
2 2 2 2 2 2 2 f f 2 2 2 2 . . . 
2 f f f f f f f f f 2 2 2 . . . 
. 2 f 2 f 2 2 2 2 2 2 2 . . . . 
. . 2 f f f f f f f 2 . . . . . 
. . 2 2 2 2 2 2 2 2 2 . . . . . 
. . 2 2 2 2 . 2 2 2 2 . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . 2 2 . . . . 
. . . . 2 2 2 2 2 2 2 f 2 . . . 
. . . . 2 f f f f 2 2 2 . . . . 
. . . 2 2 2 2 2 2 f f f 2 . . . 
. . 2 2 f f f f f f 2 2 . . . . 
. . 2 f f f f f f f 2 . . . . . 
. . 2 f 2 2 2 2 2 2 2 . . . . . 
. . 2 f f f f f f f 2 . . . . . 
. 2 2 2 2 2 2 f 2 2 2 . . . . . 
2 2 2 2 2 2 2 f f 2 2 2 2 . . . 
2 f f f f f f f f f 2 2 . . . . 
. 2 f 2 f 2 2 2 2 2 2 2 . . . . 
. . 2 f f f f f f f 2 . . . . . 
. . 2 2 2 2 2 2 2 2 2 . . . . . 
. . 2 2 2 2 . 2 2 2 2 . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . 2 . . . . 
. . . . 2 2 2 2 2 2 2 . . . . . 
. . . . 2 f f f f 2 2 2 . . . . 
. . . 2 2 2 2 2 2 f f . . . . . 
. . 2 2 f f f f f f 2 2 . . . . 
. . 2 f f f f f f f 2 . . . . . 
. . 2 f 2 2 2 2 2 2 2 . . . . . 
. . 2 f f f f f f f 2 . . . . . 
. 2 2 2 2 2 2 f 2 2 2 . . . . . 
2 2 2 2 2 2 2 f f 2 2 . . . . . 
2 f f f f f f f f f 2 2 . . . . 
. 2 f 2 f 2 2 2 2 2 2 . . . . . 
. . 2 f f f f f f f 2 . . . . . 
. . 2 2 2 2 2 2 2 2 2 . . . . . 
. . 2 2 2 2 . 2 2 2 2 . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . 2 2 2 2 2 . 2 . . . . . 
. . . . 2 f f f f 2 . . . . . . 
. . . 2 2 2 2 2 2 f f . . . . . 
. . 2 2 f f f f f f . . . . . . 
. . 2 f f f f f f f 2 . . . . . 
. . 2 f 2 2 2 2 2 2 . . . . . . 
. . 2 f f f f f f f 2 . . . . . 
. 2 2 2 2 2 2 f 2 2 . . . . . . 
2 2 2 2 2 2 2 f f 2 2 . . . . . 
2 f f f f f f f f f . . . . . . 
. 2 f 2 f 2 2 2 2 2 2 . . . . . 
. . 2 f f f f f f f . . . . . . 
. . 2 2 2 2 2 2 2 2 2 . . . . . 
. . 2 2 2 2 . 2 2 2 . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . 2 2 2 2 2 . . . . . . . 
. . . . 2 f f f . 2 . . . . . . 
. . . 2 2 2 2 2 2 . . . . . . . 
. . 2 2 f f f f f f . . . . . . 
. . 2 f f f f f f . . . . . . . 
. . 2 f 2 2 2 2 2 2 . . . . . . 
. . 2 f f f f f f . . . . . . . 
. 2 2 2 2 2 2 f 2 2 . . . . . . 
2 2 2 2 2 2 2 f f . . . . . . . 
2 f f f f f f f f f . . . . . . 
. 2 f 2 f 2 2 2 2 . . . . . . . 
. . 2 f f f f f f f . . . . . . 
. . 2 2 2 2 2 2 2 . . . . . . . 
. . 2 2 2 2 . 2 2 2 . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . 2 2 2 . 2 . . . . . . . 
. . . . 2 f f f . . . . . . . . 
. . . 2 2 2 2 2 2 . . . . . . . 
. . 2 2 f f f f . . . . . . . . 
. . 2 f f f f f f . . . . . . . 
. . 2 f 2 2 2 2 . . . . . . . . 
. . 2 f f f f f f . . . . . . . 
. 2 2 2 2 2 2 f . . . . . . . . 
2 2 2 2 2 2 2 f f . . . . . . . 
2 f f f f f f f . . . . . . . . 
. 2 f 2 f 2 2 2 2 . . . . . . . 
. . 2 f f f f f . . . . . . . . 
. . 2 2 2 2 2 2 2 . . . . . . . 
. . 2 2 2 2 . 2 . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . 2 2 2 . . . . . . . . . 
. . . . 2 f . f . . . . . . . . 
. . . 2 2 2 2 . . . . . . . . . 
. . 2 2 f f f f . . . . . . . . 
. . 2 f f f f . . . . . . . . . 
. . 2 f 2 2 2 2 . . . . . . . . 
. . 2 f f f f . . . . . . . . . 
. 2 2 2 2 2 2 f . . . . . . . . 
2 2 2 2 2 2 2 . . . . . . . . . 
2 f f f f f f f . . . . . . . . 
. 2 f 2 f 2 2 . . . . . . . . . 
. . 2 f f f f f . . . . . . . . 
. . 2 2 2 2 2 . . . . . . . . . 
. . 2 2 2 2 . 2 . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . 2 . 2 . . . . . . . . . 
. . . . 2 f . . . . . . . . . . 
. . . 2 2 2 2 . . . . . . . . . 
. . 2 2 f f . . . . . . . . . . 
. . 2 f f f f . . . . . . . . . 
. . 2 f 2 2 . . . . . . . . . . 
. . 2 f f f f . . . . . . . . . 
. 2 2 2 2 2 . . . . . . . . . . 
2 2 2 2 2 2 2 . . . . . . . . . 
2 f f f f f . . . . . . . . . . 
. 2 f 2 f 2 2 . . . . . . . . . 
. . 2 f f f . . . . . . . . . . 
. . 2 2 2 2 2 . . . . . . . . . 
. . 2 2 2 2 . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . 2 . . . . . . . . . . . 
. . . . 2 f . . . . . . . . . . 
. . . 2 2 2 . . . . . . . . . . 
. . 2 2 f f . . . . . . . . . . 
. . 2 f f f . . . . . . . . . . 
. . 2 f 2 2 . . . . . . . . . . 
. . 2 f f f . . . . . . . . . . 
. 2 2 2 2 2 . . . . . . . . . . 
2 2 2 2 2 2 . . . . . . . . . . 
2 f f f f f . . . . . . . . . . 
. 2 f 2 f 2 . . . . . . . . . . 
. . 2 f f f . . . . . . . . . . 
. . 2 2 2 2 . . . . . . . . . . 
. . 2 2 2 2 . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . 2 f . . . . . . . . . . 
. . . 2 2 . . . . . . . . . . . 
. . 2 2 f f . . . . . . . . . . 
. . 2 f f . . . . . . . . . . . 
. . 2 f 2 2 . . . . . . . . . . 
. . 2 f f . . . . . . . . . . . 
. 2 2 2 2 2 . . . . . . . . . . 
2 2 2 2 2 . . . . . . . . . . . 
2 f f f f f . . . . . . . . . . 
. 2 f 2 f . . . . . . . . . . . 
. . 2 f f f . . . . . . . . . . 
. . 2 2 2 . . . . . . . . . . . 
. . 2 2 2 2 . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . 2 . . . . . . . . . . . 
. . . 2 . . . . . . . . . . . . 
. . 2 . f . . . . . . . . . . . 
. . 2 f . . . . . . . . . . . . 
. . 2 f 2 . . . . . . . . . . . 
. . 2 f . . . . . . . . . . . . 
. 2 2 2 2 . . . . . . . . . . . 
2 2 2 2 . . . . . . . . . . . . 
2 f f f f . . . . . . . . . . . 
. 2 f 2 . . . . . . . . . . . . 
. . 2 f f . . . . . . . . . . . 
. . 2 2 . . . . . . . . . . . . 
. . 2 2 2 . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . 2 . . . . . . . . . . . . 
. . 2 . . . . . . . . . . . . . 
. . . f . . . . . . . . . . . . 
. . 2 . . . . . . . . . . . . . 
. . 2 f . . . . . . . . . . . . 
. 2 2 . . . . . . . . . . . . . 
2 2 2 2 . . . . . . . . . . . . 
2 f f . . . . . . . . . . . . . 
. 2 f 2 . . . . . . . . . . . . 
. . 2 . . . . . . . . . . . . . 
. . 2 2 . . . . . . . . . . . . 
. . 2 . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . 2 . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . 2 . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . 2 . . . . . . . . . . . . . 
2 2 . . . . . . . . . . . . . . 
2 f f . . . . . . . . . . . . . 
. 2 . . . . . . . . . . . . . . 
. . 2 . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . 2 . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. 2 . . . . . . . . . . . . . . 
2 . . . . . . . . . . . . . . . 
. 2 . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
2 . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
1 . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
2 . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
1 . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`];
            case "Walking RIght Animation":
            case "anim3":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . d d d . . . 
. . . . d d d d d d d f d . . . 
. . . . d f f f f f f f d . . . 
. . . d d f f f f f f f d . . . 
. . d d f f f f f f d d d . . . 
. . d f f f f f f f d . . . . . 
. . d f f f f f f f d . . . . . 
. . d f f f f f f f d . . . . . 
. . d f f d d f f d d . . . . . 
d d d f f d d f f d d d d . . . 
d f f f f f f f f f d f d . . . 
. d f f f f f f f f d d . . . . 
. . d f f f f f f f d . . . . . 
. . d f f d d d f f d . . . . . 
. . d d d d . d d d d . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . d d d . . . 
. . . . d d d d d d d f d . . . 
. . . d d f f f f f f f d . . . 
. . d d f f f f f f d d d . . . 
. . d f f f f f f f d . . . . . 
. . d f f f f f f f d . . . . . 
. . d f f f f f f f d . . . . . 
. . d f f d d f f d d d d . . . 
d d d f f d d f f d d f d . . . 
d f f f f f f f f f d d . . . . 
. d f f f f f f f f d . . . . . 
. . d f f f f f f f d . . . . . 
. . d f f d d d d d d . . . . . 
. . d d d d . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . d d d . . . 
. . . d d d d d d d d f d . . . 
. . d d d f f f f f f f d . . . 
. . d f f f f f f f d d d . . . 
. . d f f f f f f f d . . . . . 
. . d f f f f f f f d . . . . . 
. . d f f d d f f d d . . . . . 
d d d f f d d f f d d d d . . . 
d f f f f f f f f f d f d . . . 
. d f f f f f f f f d d . . . . 
. . d f f f f f f f d . . . . . 
. . d f f d d d f f d . . . . . 
. . d d d d . d d d d . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . d d d . . . 
. . . . d d d d d d d f d . . . 
. . . d d f f f f f f f d . . . 
. . d d f f f f f f d d d . . . 
. . d f f f f f f f d . . . . . 
. . d f f f f f f f d . . . . . 
. . d f f f f f f f d . . . . . 
d d d f f d d f f d d . . . . . 
d f f f f d d f f d d d d . . . 
. d f f f f f f f f d f d . . . 
. d f f f f f f f f d d . . . . 
. . d f f f f f f f d . . . . . 
. . d d d d d d f f d . . . . . 
. . . . . . . d d d d . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . d d d . . . 
. . . . d d d d d d d f d . . . 
. . . . d f f f f f f f d . . . 
. . . d d f f f f f f f d . . . 
. . d d f f f f f f d d d . . . 
. . d f f f f f f f d . . . . . 
. . d f f f f f f f d . . . . . 
. . d f f f f f f f d . . . . . 
. . d f f d d f f d d . . . . . 
d d d f f d d f f d d d d . . . 
d f f f f f f f f f d f d . . . 
. d f f f f f f f f d d . . . . 
. . d f f f f f f f d . . . . . 
. . d f f d d d f f d . . . . . 
. . d d d d . d d d d . . . . . 
`];
            case "Walking Left Animation":
            case "anim4":return [img`
. . . . . . . . . . . . . . . . 
. . . d d d . . . . . . . . . . 
. . . d f d d d d d d d . . . . 
. . . d f f f f f f f d . . . . 
. . . d f f f f f f f d d . . . 
. . . d d d f f f f f f d d . . 
. . . . . d f f f f f f f d . . 
. . . . . d f f f f f f f d . . 
. . . . . d f f f f f f f d . . 
. . . . . d d f f d d f f d . . 
. . . d d d d f f d d f f d d d 
. . . d f d f f f f f f f f f d 
. . . . d d f f f f f f f f d . 
. . . . . d f f f f f f f d . . 
. . . . . d f f d d d f f d . . 
. . . . . d d d d . d d d d . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . d d d . . . . . . . . . . 
. . . d f d d d d d d d . . . . 
. . . d f f f f f f f d d . . . 
. . . d d d f f f f f f d d . . 
. . . . . d f f f f f f f d . . 
. . . . . d f f f f f f f d . . 
. . . . . d f f f f f f f d . . 
. . . d d d d f f d d f f d . . 
. . . d f d d f f d d f f d d d 
. . . . d d f f f f f f f f f d 
. . . . . d f f f f f f f f d . 
. . . . . d f f f f f f f d . . 
. . . . . d d d d d d f f d . . 
. . . . . . . . . . d d d d . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . d d d . . . . . . . . . . 
. . . d f d d d d d d d d . . . 
. . . d f f f f f f f d d d . . 
. . . d d d f f f f f f f d . . 
. . . . . d f f f f f f f d . . 
. . . . . d f f f f f f f d . . 
. . . . . d d f f d d f f d . . 
. . . d d d d f f d d f f d d d 
. . . d f d f f f f f f f f f d 
. . . . d d f f f f f f f f d . 
. . . . . d f f f f f f f d . . 
. . . . . d f f d d d f f d . . 
. . . . . d d d d . d d d d . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . d d d . . . . . . . . . . 
. . . d f d d d d d d d . . . . 
. . . d f f f f f f f d d . . . 
. . . d d d f f f f f f d d . . 
. . . . . d f f f f f f f d . . 
. . . . . d f f f f f f f d . . 
. . . . . d f f f f f f f d . . 
. . . . . d d f f d d f f d d d 
. . . d d d d f f d d f f f f d 
. . . d f d f f f f f f f f d . 
. . . . d d f f f f f f f f d . 
. . . . . d f f f f f f f d . . 
. . . . . d f f d d d d d d . . 
. . . . . d d d d . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . d d d . . . . . . . . . . 
. . . d f d d d d d d d . . . . 
. . . d f f f f f f f d . . . . 
. . . d f f f f f f f d d . . . 
. . . d d d f f f f f f d d . . 
. . . . . d f f f f f f f d . . 
. . . . . d f f f f f f f d . . 
. . . . . d f f f f f f f d . . 
. . . . . d d f f d d f f d . . 
. . . d d d d f f d d f f d d d 
. . . d f d f f f f f f f f f d 
. . . . d d f f f f f f f f d . 
. . . . . d f f f f f f f d . . 
. . . . . d f f d d d f f d . . 
. . . . . d d d d . d d d d . . 
`];
        }
        return null;
    })

}
// Auto-generated code. Do not edit.
